---
language: generic

services:
  - docker

os: linux
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get install --reinstall ca-certificates
  - update-ca-certificates

script:
  - make build.image
