---
apiVersion: v1
kind: Service
metadata:
  name: quote
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http-api
  selector:
    app: quote

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
        - name: quote-service-api
          image: plombardi89/quote
          imagePullPolicy: Always
          ports:
            - name: http-api
              containerPort: 8080